/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Avatar: typeof import('@nextui-org/react')['Avatar']
  const Button: typeof import('@nextui-org/react')['Button']
  const ButtonGroup: typeof import('@nextui-org/react')['ButtonGroup']
  const Card: typeof import('@nextui-org/react')['Card']
  const Input: typeof import('@nextui-org/react')['Input']
  const Modal: typeof import('@nextui-org/react')['Modal']
  const Tooltip: typeof import('@nextui-org/react')['Tooltip']
}
